<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-R0E149I" failures="0" tests="2" name="com.empire.qa.testcases.AddinventorypageTest" time="15.033" errors="1" timestamp="2023-11-06T10:05:59 IST" skipped="0">
  <testcase classname="com.empire.qa.testcases.AddinventorypageTest" name="VerifyaddinventoryTitle" time="14.075"/>
  <testcase classname="com.empire.qa.testcases.AddinventorypageTest" name="VerifyAddInventoryTest" time="0.958">
    <error message="
[public void com.empire.qa.testcases.AddinventorypageTest.VerifyAddInventoryTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: VerifyAddInventoryTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8, java.lang.String arg9, java.lang.String arg10, java.lang.String arg11, java.lang.String arg12, java.lang.String arg13, java.lang.String arg14, java.lang.String arg15, java.lang.String arg16, java.lang.String arg17])
Arguments: [(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.empire.qa.testcases.AddinventorypageTest.VerifyAddInventoryTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Throwable] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: VerifyAddInventoryTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7, java.lang.String arg8, java.lang.String arg9, java.lang.String arg10, java.lang.String arg11, java.lang.String arg12, java.lang.String arg13, java.lang.String arg14, java.lang.String arg15, java.lang.String arg16, java.lang.String arg17])
Arguments: [(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001,(java.lang.String) EMP001]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAddInventoryTest -->
</testsuite> <!-- com.empire.qa.testcases.AddinventorypageTest -->
